### ISSUE TITLE
Gouwen en ploegen op de kaart

### ISSUE THREAD

**Issue by TinusVL** [ScoutsGidsenVL/ho-gids-2022#1]
Als je via Nieuws > Praktische informatie gaat, vind je gemakkelijk op welke grond je moet zijn voor een bepaalde gouw of ploeg.
Als je rechtstreeks de kaart opent, vind je niet terug wie waar zit.

Daarom stel ik voor om op de kaart de naam van elke gouw- of ploeggrond te veranderen van bijvoorbeeld 'Kamp 7' naar 'Kamp 7: Waas en Zuid-West-Vlaanderen' (afgekort indien nodig).

Lijkt je dit een goed idee?

**Comment by mstuyven** [comment]
Toegevoegd!
